### ISSUE TITLE
2.6 handles input with less than 9 bytes incorrectly

### ISSUE THREAD

**Issue by ilovezfs** [andre-simon/ansifilter#7]
ansifilter 2.5 when applied to a file containing `f\x1b[31moo`, but not ending in a new line character, will print `foo`.

ansifilter 2.6 when applied to the same file will print blank output.

If the file instead contains `f\x1b[31moo\n` then 2.6 is able to handle it correctly and will print `foo`.

**Comment by andre-simon** [comment]
This bug is triggered by input with less than 9 bytes. Ansifilter checks if the file starts with a Tundra magic sequence and does not reset the input stream correctly. Ansifilter 2.5 has the same problem, but only with input of 4 or less bytes (to check for a XBIN sequence). Fix is committed, release will follow shortly.

**Comment by ilovezfs** [comment]
@andre-simon thanks!

**Comment by andre-simon** [comment]
Fixed in 2.7.

**Comment by ilovezfs** [comment]
@andre-simon Thanks: https://github.com/Homebrew/homebrew-core/pull/16419
 
:)
